### PR TITLE
add ability to reset targets per task or for the whole manifest

### PR DESCRIPTION
**Pull request by loisgomez**
Adds the ability to reset the last execution
- Task by task
- Whole manifest

Ex: 

- **dnit clean**
- **dnit clean build_javaserver yarn_client**

### CODE REVIEW

**Comment by PaulThompson** [comment]
Thanks @loisgomez - That looks good.  I added a few more commits to make it have a test for the feature

https://github.com/PaulThompson/dnit/tree/feature-clean

Could you add those commits to the PR?

**Comment by loisgomez** [comment]
Updated @PaulThompson
Thanks a lot!

**Comment by loisgomez** [comment]
@PaulThompson Any chance to kickoff a new tag release with the latest changes? Thanks!

**Comment by PaulThompson** [comment]
Done v1.14.3

https://deno.land/x/dnit@dnit-v1.14.3/main.ts

**Pull request merged**
